### ISSUE TITLE
Possible misrendering of number in description strings

### ISSUE THREAD

**Issue by rYR79435** [wvanderp/isOsmComplete#3]
Shouldn't strings like, e.g., https://github.com/wvanderp/isOsmComplete/blob/main/data/compare.json#L38 render the `{{expected}}` number?

**Comment by wvanderp** [comment]
You are totally right. I have fixed it in 072b44ae7e529aaeb7df13979dad2ea60672634b

I've added the `{{expected}}` everywhere but left the code from `{{actual}}` because I have a feeling I'll need it later.

Thank you for pointing it out
